env:
  browser: true
globals:
  require: false
  riot: false
  DetectRTC: false
  app: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
    - singleValue: false
  no-magic-numbers:
    - error
    - ignoreArrayIndexes: true
